### ISSUE TITLE
don't save source commands in history

### ISSUE THREAD

**Issue by jmpohl** [dgrisham/wenv#39]
a la [this](https://superuser.com/questions/352788/how-to-prevent-a-command-in-the-zshell-from-being-saved-into-history) method

**Comment by dgrisham** [comment]
Ah nice, before I put this all into a script I think I was doing a similar thing (or I couldn't get it to work). Will test soon :ok_hand:

**Comment by dgrisham** [comment]
Ah, I think I remember one issue here. When I do this, it removes it from my history file for future shell instances, but when I up-arrow commands in the same shell where the space-prefixed command ran the command is still in my history for that shell. I'm not sure if that's local to my setup/how to make sure the command never shows up in a non-hacky way, still have to look for more solutions.

**Comment by dgrisham** [comment]
Okay I was a bit wrong there (I was setting the option incorrectly), here's the closest solution I've come up with:

```
tmux send -t "$wenv" "setopt -o histignorespace" ENTER " source $tmp_start_file && rm -f $tmp_start_file" ENTER " " ENTER
```

Two things:

- The `setopt -o histignorespace` is still in the history, even if you prefix it with a space
- Because this `source`'s the wenv's startup file, it has to run in the same shell that we drop the user into, which means the `setopt` changes whatever the user had set. We could save the value with `old_histignorespace=$options[histignorespace]` (which returns `on` or `off`), then use that to reset the value after. But note that, when we reset the option to it's original value, if that original value was `off` then that second `setopt` command also remains in the history. So then we end up with three commands in the history (`old_histignorespace='...'`, `setopt -o histignorespace`, and `setopt` back to the original value somehow), rather than the one we have now.

So I looked into editing the zsh history directly, which seems to get messy... https://unix.stackexchange.com/questions/236094/how-to-remove-the-last-command-or-current-command-for-bonus-from-zsh-history/605328

Starting to remember why I never did this haha. Feel free to search for other solutions here, maybe there's another option I'm not seeing.

**Comment by jmpohl** [comment]
I'm thinking one of two things. I did find [this](https://unix.stackexchange.com/questions/48305/how-can-i-run-a-command-in-zsh-without-pushing-it-onto-the-current-sessions-his) additional insight into the `setopt histignorespace` command. Not sure how you were testing whether or not it was in your history, but if you were just up arrowing it wouldn't necessarily confirm that it was being saved into your history. Maybe try reverse-i-search to check it instead?

Other than that, I think I am happy to have this option set in my shell all the time so just adding the space and maybe noting this in the documentation is the other way I would go about this which might just be the cleaner solution here 

¯\\_(ツ)_/¯

**Comment by dgrisham** [comment]
Totally re: your first point, I think I was setting `set +o histignorespace`, but I should've been doing `set -o histignorespace`.

Your second point actually makes a lot of sense. If we just prefix with a space, then it doesn't really make a difference to anyone without the option set, but gives an easy way to wipe that command if they do have it set. The only case we miss is someone who has the option set in their shell but *doesn't* want the wenv source command to be wiped from their history, but at this point that person doesn't exist and isn't worth caring about.

**Comment by jmpohl** [comment]
Do we want to do the `setopt` stuff? Which way do you prefer?

**Comment by dgrisham** [comment]
Well, I tried doing it how you suggested (set the option in my `zshrc` then prefix the command with a space) but it's still not quite there. It's kind of ridiculous, might be easiest to explain on a call.

**Comment by jmpohl** [comment]
I'm getting weird stuff too...

**Comment by jmpohl** [comment]
I'm free for a call if you want to hop on the jitsi

**Comment by dgrisham** [comment]
Closing via https://github.com/dgrisham/wenv/commit/0822b7c7a019c7747986b59caec891a23d02b094
